server:
  port: 9091

#dev|local
spring:
  profiles:
    active: dev

  application:
    name: RESTAURANT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
#ddl-auto: updat-update table data only|create- when run each table will create new 